SELF_DIR := $(dir $(lastword $(MAKEFILE_LIST)))

%.vhdl: %.vhd.c
	gcc -E -nostdinc -undef -P -w $< -I$(SELF_DIR) -o $@
	cp $@ $@.debug

%.vhd.c: %.vhdx
	$(SELF_DIR)/bin/hash-for < $< > $@
	cp $@ $@.debug
