SELF_DIR := $(dir $(lastword $(MAKEFILE_LIST)))

test: $(patsubst %.vhdx,%.vhdl,$(wildcard tests/*.vhdx))

$(SELF_DIR)/lib/vhdx-filter.so: $(SELF_DIR)/tools/o-creat.c $(SELF_DIR)/tools/vhdx-filter.c
	gcc -shared -fPIC -ldl -fpic $^ -o $@

%.vhdl: %.vhd.c $(SELF_DIR)/lib/vhdx-filter.so
	$(shell PATH=$(PATH):$(SELF_DIR)/bin LD_PRELOAD=$(SELF_DIR)/lib/vhdx-filter.so gcc -E -nostdinc -undef -P -w $< -I$(SELF_DIR) $(GCCFLAGS) -o $@)
	cp $@ $@.debug

%.vhd.c: %.vhdx
	cp $< $@
